apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAzureContainerAllowedPortsBad
metadata:
  name: container-allowed-ports-bad
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedPorts: {{ .Values.allowedContainerPorts }}
